theme: jekyll-theme-minimal
title: Talk Dim Sum
description: your dim sum companion
show_downloads: true
logo: /images/icons/cat/catglasses.svg
appstore: https://apps.apple.com/us/app/talk-dim-sum/id953929066
privacy: This app does not collect any data
