theme: jekyll-theme-minimal
title: Talk Dim Sum
description: your dim sum companion
show_downloads: true
logo: /images/dakotasnow/CatGraphic300x300.jpg
appstore: https://apps.apple.com/us/app/talk-dim-sum/id953929066
