name: talkdimsum
description: Your dim sum companion

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.7+25

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
 # flutter_sheet_localization: ">=5.1.1"
 # flutter_localizations:
#    sdk: flutter
 # intl:      

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:

  # more stuff
  app_settings:
  bubble:
#  camera:
  cupertino_search:
    git: 
      url: https://github.com/technicat/cupertino_search
  flutter_markdown:
  flutter_riverpod:
  flutter_tts:
  freezed_annotation:
  get:
  google_ml_kit:
  json_annotation: ">=4.4.0"
  material_search:
    git: 
      url: https://github.com/technicat/material_search
  path:
  provider:
  share:
  shared_preferences:
  speech_to_text:
  sprintf:
  sqflite:
  url_launcher:

# run this first
# flutter pub run build_runner build --delete-conflicting-outputs

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_sheet_localization_generator:  ">=5.1.7"
  flutter_launcher_icons:
  build_runner:
  json_serializable:
  freezed:
  lints:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
#  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  assets: 
    - assets/images/
    - assets/json/
    - assets/json/dish/
    - assets/json/place/
    - assets/json/words/
    - assets/json/phrases/
    - graphics/

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true 
  ios: true
  remove_alpha_ios: true
  image_path: "graphics/if_dim_sum.png"
